
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbgjeoiihklyondzzeim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1iZ2plb2lpaGtseW9uZHp6ZWltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwNjY3NTYsImV4cCI6MjA1ODY0Mjc1Nn0.9JkJHyrA0ROQfBa-YjkbXMCGdgsDfKcaL_Fq1alrQjM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Let's make sure the database schema is up to date
// Adding phone column to bikes table
(async () => {
  const { error } = await supabase.rpc('add_phone_column_if_missing');
  if (error && !error.message.includes('function "add_phone_column_if_missing" does not exist')) {
    console.error('Error adding phone column:', error);
  }
})();
