
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbgjeoiihklyondzzeim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1iZ2plb2lpaGtseW9uZHp6ZWltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwNjY3NTYsImV4cCI6MjA1ODY0Mjc1Nn0.9JkJHyrA0ROQfBa-YjkbXMCGdgsDfKcaL_Fq1alrQjM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
